### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [asimakiskydros/QuaCiDe#1]
I recently came across your project QuaCiDe and I noticed that the repository github.com/asimakiskydros/QuaCiDe currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by asimakiskydros** [comment]
Hello Dr. Cruz-Benito, 

thank you for this suggestion! This project sits in an intermediary stage where it's not yet ready for F/OSS release but I had to open it publicly for other reasons. As such, I deliberately didn't add a license. Rest assured that, when the time comes, I will add the appropriate license, as it's a major goal of the project to be completely open source.

Thanks again!

**Comment by cbjuan** [comment]
ok, thanks!
